(** This file has been generated by the Catala compiler, do not edit! *)

open Runtime

[@@@ocaml.warning "-26-27-32"]

type violation =
  | Section286_102 of unit
  | Section286_122 of unit
  | Section286_130 of unit
  | Section286_131 of unit
  | Section286_132 of unit
  | Section286_133 of unit
  | Section286_134 of unit
  | Section286_83_135 of unit
  | Section291_2 of unit
  | Section291_3_1 of unit
  | Section291_3_2 of unit
  | Section291_3_3 of unit
  | Section291_4_6 of unit
  | Section291_8 of unit
  | Section291_9 of unit
  | Section291_11_5 of unit
  | Section291_11_6 of unit
  | Section291_11 of unit
  | Section291_12 of unit
  | Section291_13 of unit
  | Section291_14 of unit



type fund =
  | NeuroTrauma of unit
  | TraumaSystem of unit
  | Clerk of unit



type fee_category =
  | Paragraph7 of unit
  | Paragraph8 of unit
  | Paragraph9 of unit



type fine = {
  min_fine: money;
  max_fine: money;
}



type imprisonment = {
  min_days: duration;
  max_days: duration;
}



type offense = {
  date_of: date;
  violation: violation;
}



type fee = {
  min_fee: money;
  max_fee: money;
  fund: fund;
}



type defendant = {
  priors: offense array;
  age: integer;
}



type penalty_ =
  | Imprisonment of imprisonment
  | Fine of fine
  | Fee of fee
  | LoseRightToDriveUntil18 of unit



type penalty =
  | One of penalty_
  | Either of penalty_ array



type s_286_136_out = {
  offense_out: offense;
  defendant_out: defendant;
  max_fine_out: money;
  min_fine_out: money;
  max_days_out: duration;
  priors_same_offense_out: integer;
  paragraph_b_applies_out: bool;
  paragraph_c_applies_out: bool;
  penalties_out: penalty array;
}



type s_286_136_in = {
  offense_in: unit -> offense;
  defendant_in: unit -> defendant;
  max_fine_in: unit -> money;
  min_fine_in: unit -> money;
  max_days_in: unit -> duration;
  priors_same_offense_in: unit -> integer;
  paragraph_b_applies_in: unit -> bool;
  paragraph_c_applies_in: unit -> bool;
  penalties_in: unit -> (penalty array);
}



type s_291_11_6_out = {
  penalties_out: penalty array;
}



type s_291_11_6_in = {
  penalties_in: unit -> (penalty array);
}



type s_607_4_out = {
  violation_out: violation;
  category_out: fee_category;
  penalty_out: penalty;
}



type s_607_4_in = {
  violation_in: unit -> violation;
  category_in: unit -> fee_category;
  penalty_in: unit -> penalty;
}





let s_286_136 =
  fun (s_286_136_in: s_286_136_in) ->
    let offense_ : unit -> offense = (s_286_136_in.offense_in)
    in
    let defendant_ : unit -> defendant = (s_286_136_in.defendant_in)
    in
    let max_fine_ : unit -> money = (s_286_136_in.max_fine_in)
    in
    let min_fine_ : unit -> money = (s_286_136_in.min_fine_in)
    in
    let max_days_ : unit -> duration = (s_286_136_in.max_days_in)
    in
    let priors_same_offense_ : unit -> integer =
      (s_286_136_in.priors_same_offense_in)
    in
    let paragraph_b_applies_ : unit -> bool =
      (s_286_136_in.paragraph_b_applies_in)
    in
    let paragraph_c_applies_ : unit -> bool =
      (s_286_136_in.paragraph_c_applies_in)
    in
    let penalties_ : unit -> (penalty array) = (s_286_136_in.penalties_in)
    in
    let offense_ : offense =
      ((try
          (handle_default ([|(fun (_: _) -> offense_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default ([||]) (fun (_: _) -> false)
                  (fun (_: _) -> raise EmptyError))) with EmptyError ->
          (raise NoValueProvided)))
    in
    let defendant_ : defendant =
      ((try
          (handle_default ([|(fun (_: _) -> defendant_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default ([||]) (fun (_: _) -> false)
                  (fun (_: _) -> raise EmptyError))) with EmptyError ->
          (raise NoValueProvided)))
    in
    let max_fine_ : money =
      ((try
          (handle_default ([|(fun (_: _) -> max_fine_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||]) (fun (_: _) -> true)
                          (fun (_: _) -> money_of_cents_string "100000"))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    let paragraph_c_applies_ : bool =
      ((try
          (handle_default ([|(fun (_: _) -> paragraph_c_applies_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||])
                          (fun (_: _) ->
                             ((defendant_.age) <! (integer_of_string "18")))
                          (fun (_: _) -> true))|]) (fun (_: _) -> true)
                  (fun (_: _) -> false))) with EmptyError -> (raise
          NoValueProvided)))
    in
    let priors_same_offense_ : integer =
      ((try
          (handle_default ([|(fun (_: _) -> priors_same_offense_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||]) (fun (_: _) -> true)
                          (fun (_: _) ->
                             Array.fold_left
                               (fun (acc_: integer) (prior_: _) ->
                                   if
                                    (((prior_.violation) =
                                        (offense_.violation)) &&
                                       (((prior_.date_of) +@
                                           (duration_of_numbers 5 0 0)) >=@
                                          (offense_.date_of))) then
                                    (acc_ +! (integer_of_string "1")) else
                                    acc_) (integer_of_string "0")
                               (defendant_.priors)))|]) (fun (_: _) -> false)
                  (fun (_: _) -> raise EmptyError))) with EmptyError ->
          (raise NoValueProvided)))
    in
    let paragraph_b_applies_ : bool =
      ((try
          (handle_default ([|(fun (_: _) -> paragraph_b_applies_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||])
                          (fun (_: _) ->
                             (((match (offense_.violation)
                                 with
                                 Section286_102 _ -> true
                                 | Section286_122 _ -> false
                                 | Section286_130 _ -> false
                                 | Section286_131 _ -> false
                                 | Section286_132 _ -> false
                                 | Section286_133 _ -> false
                                 | Section286_134 _ -> false
                                 | Section286_83_135 _ -> false
                                 | Section291_2 _ -> false
                                 | Section291_3_1 _ -> false
                                 | Section291_3_2 _ -> false
                                 | Section291_3_3 _ -> false
                                 | Section291_4_6 _ -> false
                                 | Section291_8 _ -> false
                                 | Section291_9 _ -> false
                                 | Section291_11_5 _ -> false
                                 | Section291_11_6 _ -> false
                                 | Section291_11 _ -> false
                                 | Section291_12 _ -> false
                                 | Section291_13 _ -> false
                                 | Section291_14 _ -> false) ||
                                 ((match (offense_.violation)
                                    with
                                    Section286_102 _ -> false
                                    | Section286_122 _ -> true
                                    | Section286_130 _ -> false
                                    | Section286_131 _ -> false
                                    | Section286_132 _ -> false
                                    | Section286_133 _ -> false
                                    | Section286_134 _ -> false
                                    | Section286_83_135 _ -> false
                                    | Section291_2 _ -> false
                                    | Section291_3_1 _ -> false
                                    | Section291_3_2 _ -> false
                                    | Section291_3_3 _ -> false
                                    | Section291_4_6 _ -> false
                                    | Section291_8 _ -> false
                                    | Section291_9 _ -> false
                                    | Section291_11_5 _ -> false
                                    | Section291_11_6 _ -> false
                                    | Section291_11 _ -> false
                                    | Section291_12 _ -> false
                                    | Section291_13 _ -> false
                                    | Section291_14 _ -> false) ||
                                    ((match (offense_.violation)
                                       with
                                       Section286_102 _ -> false
                                       | Section286_122 _ -> false
                                       | Section286_130 _ -> true
                                       | Section286_131 _ -> false
                                       | Section286_132 _ -> false
                                       | Section286_133 _ -> false
                                       | Section286_134 _ -> false
                                       | Section286_83_135 _ -> false
                                       | Section291_2 _ -> false
                                       | Section291_3_1 _ -> false
                                       | Section291_3_2 _ -> false
                                       | Section291_3_3 _ -> false
                                       | Section291_4_6 _ -> false
                                       | Section291_8 _ -> false
                                       | Section291_9 _ -> false
                                       | Section291_11_5 _ -> false
                                       | Section291_11_6 _ -> false
                                       | Section291_11 _ -> false
                                       | Section291_12 _ -> false
                                       | Section291_13 _ -> false
                                       | Section291_14 _ -> false) ||
                                       ((match (offense_.violation)
                                          with
                                          Section286_102 _ -> false
                                          | Section286_122 _ -> false
                                          | Section286_130 _ -> false
                                          | Section286_131 _ -> true
                                          | Section286_132 _ -> false
                                          | Section286_133 _ -> false
                                          | Section286_134 _ -> false
                                          | Section286_83_135 _ -> false
                                          | Section291_2 _ -> false
                                          | Section291_3_1 _ -> false
                                          | Section291_3_2 _ -> false
                                          | Section291_3_3 _ -> false
                                          | Section291_4_6 _ -> false
                                          | Section291_8 _ -> false
                                          | Section291_9 _ -> false
                                          | Section291_11_5 _ -> false
                                          | Section291_11_6 _ -> false
                                          | Section291_11 _ -> false
                                          | Section291_12 _ -> false
                                          | Section291_13 _ -> false
                                          | Section291_14 _ -> false) ||
                                          ((match (offense_.violation)
                                             with
                                             Section286_102 _ -> false
                                             | Section286_122 _ -> false
                                             | Section286_130 _ -> false
                                             | Section286_131 _ -> false
                                             | Section286_132 _ -> true
                                             | Section286_133 _ -> false
                                             | Section286_134 _ -> false
                                             | Section286_83_135 _ ->
                                              false
                                             | Section291_2 _ -> false
                                             | Section291_3_1 _ -> false
                                             | Section291_3_2 _ -> false
                                             | Section291_3_3 _ -> false
                                             | Section291_4_6 _ -> false
                                             | Section291_8 _ -> false
                                             | Section291_9 _ -> false
                                             | Section291_11_5 _ -> false
                                             | Section291_11_6 _ -> false
                                             | Section291_11 _ -> false
                                             | Section291_12 _ -> false
                                             | Section291_13 _ -> false
                                             | Section291_14 _ -> false) ||
                                             ((match (offense_.violation)
                                                with
                                                Section286_102 _ -> false
                                                | Section286_122 _ ->
                                                 false
                                                | Section286_130 _ ->
                                                 false
                                                | Section286_131 _ ->
                                                 false
                                                | Section286_132 _ ->
                                                 false
                                                | Section286_133 _ ->
                                                 true
                                                | Section286_134 _ ->
                                                 false
                                                | Section286_83_135 _ ->
                                                 false
                                                | Section291_2 _ -> false
                                                | Section291_3_1 _ ->
                                                 false
                                                | Section291_3_2 _ ->
                                                 false
                                                | Section291_3_3 _ ->
                                                 false
                                                | Section291_4_6 _ ->
                                                 false
                                                | Section291_8 _ -> false
                                                | Section291_9 _ -> false
                                                | Section291_11_5 _ ->
                                                 false
                                                | Section291_11_6 _ ->
                                                 false
                                                | Section291_11 _ -> false
                                                | Section291_12 _ -> false
                                                | Section291_13 _ -> false
                                                | Section291_14 _ -> false)
                                                ||
                                                (match (offense_.violation)
                                                with
                                                Section286_102 _ -> false
                                                | Section286_122 _ ->
                                                 false
                                                | Section286_130 _ ->
                                                 false
                                                | Section286_131 _ ->
                                                 false
                                                | Section286_132 _ ->
                                                 false
                                                | Section286_133 _ ->
                                                 false
                                                | Section286_134 _ ->
                                                 true
                                                | Section286_83_135 _ ->
                                                 false
                                                | Section291_2 _ -> false
                                                | Section291_3_1 _ ->
                                                 false
                                                | Section291_3_2 _ ->
                                                 false
                                                | Section291_3_3 _ ->
                                                 false
                                                | Section291_4_6 _ ->
                                                 false
                                                | Section291_8 _ -> false
                                                | Section291_9 _ -> false
                                                | Section291_11_5 _ ->
                                                 false
                                                | Section291_11_6 _ ->
                                                 false
                                                | Section291_11 _ -> false
                                                | Section291_12 _ -> false
                                                | Section291_13 _ -> false
                                                | Section291_14 _ -> false)))))))
                                &&
                                ((priors_same_offense_ >=! (integer_of_string
                                    "2")) && (not paragraph_c_applies_))))
                          (fun (_: _) -> true))|]) (fun (_: _) -> true)
                  (fun (_: _) -> false))) with EmptyError -> (raise
          NoValueProvided)))
    in
    let max_days_ : duration =
      ((try
          (handle_default ([|(fun (_: _) -> max_days_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default
                          ([|(fun (_: _) ->
                                handle_default
                                  ([|(fun (_: _) ->
                                        handle_default ([||])
                                          (fun (_: _) -> paragraph_b_applies_)
                                          (fun (_: _) ->
                                             duration_of_numbers 1 0 0))|])
                                  (fun (_: _) ->
                                     ((match (offense_.violation)
                                        with
                                        Section286_102 _ -> true
                                        | Section286_122 _ -> false
                                        | Section286_130 _ -> false
                                        | Section286_131 _ -> false
                                        | Section286_132 _ -> false
                                        | Section286_133 _ -> false
                                        | Section286_134 _ -> false
                                        | Section286_83_135 _ -> false
                                        | Section291_2 _ -> false
                                        | Section291_3_1 _ -> false
                                        | Section291_3_2 _ -> false
                                        | Section291_3_3 _ -> false
                                        | Section291_4_6 _ -> false
                                        | Section291_8 _ -> false
                                        | Section291_9 _ -> false
                                        | Section291_11_5 _ -> false
                                        | Section291_11_6 _ -> false
                                        | Section291_11 _ -> false
                                        | Section291_12 _ -> false
                                        | Section291_13 _ -> false
                                        | Section291_14 _ -> false) ||
                                        ((match (offense_.violation)
                                           with
                                           Section286_102 _ -> false
                                           | Section286_122 _ -> true
                                           | Section286_130 _ -> false
                                           | Section286_131 _ -> false
                                           | Section286_132 _ -> false
                                           | Section286_133 _ -> false
                                           | Section286_134 _ -> false
                                           | Section286_83_135 _ -> false
                                           | Section291_2 _ -> false
                                           | Section291_3_1 _ -> false
                                           | Section291_3_2 _ -> false
                                           | Section291_3_3 _ -> false
                                           | Section291_4_6 _ -> false
                                           | Section291_8 _ -> false
                                           | Section291_9 _ -> false
                                           | Section291_11_5 _ -> false
                                           | Section291_11_6 _ -> false
                                           | Section291_11 _ -> false
                                           | Section291_12 _ -> false
                                           | Section291_13 _ -> false
                                           | Section291_14 _ -> false) ||
                                           ((match (offense_.violation)
                                              with
                                              Section286_102 _ -> false
                                              | Section286_122 _ -> false
                                              | Section286_130 _ -> true
                                              | Section286_131 _ -> false
                                              | Section286_132 _ -> false
                                              | Section286_133 _ -> false
                                              | Section286_134 _ -> false
                                              | Section286_83_135 _ ->
                                               false
                                              | Section291_2 _ -> false
                                              | Section291_3_1 _ -> false
                                              | Section291_3_2 _ -> false
                                              | Section291_3_3 _ -> false
                                              | Section291_4_6 _ -> false
                                              | Section291_8 _ -> false
                                              | Section291_9 _ -> false
                                              | Section291_11_5 _ -> false
                                              | Section291_11_6 _ -> false
                                              | Section291_11 _ -> false
                                              | Section291_12 _ -> false
                                              | Section291_13 _ -> false
                                              | Section291_14 _ -> false) ||
                                              ((match (offense_.violation)
                                                 with
                                                 Section286_102 _ -> false
                                                 | Section286_122 _ ->
                                                  false
                                                 | Section286_130 _ ->
                                                  false
                                                 | Section286_131 _ ->
                                                  true
                                                 | Section286_132 _ ->
                                                  false
                                                 | Section286_133 _ ->
                                                  false
                                                 | Section286_134 _ ->
                                                  false
                                                 | Section286_83_135 _ ->
                                                  false
                                                 | Section291_2 _ -> false
                                                 | Section291_3_1 _ ->
                                                  false
                                                 | Section291_3_2 _ ->
                                                  false
                                                 | Section291_3_3 _ ->
                                                  false
                                                 | Section291_4_6 _ ->
                                                  false
                                                 | Section291_8 _ -> false
                                                 | Section291_9 _ -> false
                                                 | Section291_11_5 _ ->
                                                  false
                                                 | Section291_11_6 _ ->
                                                  false
                                                 | Section291_11 _ ->
                                                  false
                                                 | Section291_12 _ ->
                                                  false
                                                 | Section291_13 _ ->
                                                  false
                                                 | Section291_14 _ ->
                                                  false) ||
                                                 ((match (offense_.violation)
                                                    with
                                                    Section286_102 _ ->
                                                     false
                                                    | Section286_122 _ ->
                                                     false
                                                    | Section286_130 _ ->
                                                     false
                                                    | Section286_131 _ ->
                                                     false
                                                    | Section286_132 _ ->
                                                     true
                                                    | Section286_133 _ ->
                                                     false
                                                    | Section286_134 _ ->
                                                     false
                                                    | Section286_83_135 _ ->
                                                     false
                                                    | Section291_2 _ ->
                                                     false
                                                    | Section291_3_1 _ ->
                                                     false
                                                    | Section291_3_2 _ ->
                                                     false
                                                    | Section291_3_3 _ ->
                                                     false
                                                    | Section291_4_6 _ ->
                                                     false
                                                    | Section291_8 _ ->
                                                     false
                                                    | Section291_9 _ ->
                                                     false
                                                    | Section291_11_5 _ ->
                                                     false
                                                    | Section291_11_6 _ ->
                                                     false
                                                    | Section291_11 _ ->
                                                     false
                                                    | Section291_12 _ ->
                                                     false
                                                    | Section291_13 _ ->
                                                     false
                                                    | Section291_14 _ ->
                                                     false) ||
                                                    ((match
                                                        (offense_.violation)
                                                       with
                                                       Section286_102 _ ->
                                                        false
                                                       | Section286_122 _ ->
                                                        false
                                                       | Section286_130 _ ->
                                                        false
                                                       | Section286_131 _ ->
                                                        false
                                                       | Section286_132 _ ->
                                                        false
                                                       | Section286_133 _ ->
                                                        true
                                                       | Section286_134 _ ->
                                                        false
                                                       | Section286_83_135 _ ->
                                                        false
                                                       | Section291_2 _ ->
                                                        false
                                                       | Section291_3_1 _ ->
                                                        false
                                                       | Section291_3_2 _ ->
                                                        false
                                                       | Section291_3_3 _ ->
                                                        false
                                                       | Section291_4_6 _ ->
                                                        false
                                                       | Section291_8 _ ->
                                                        false
                                                       | Section291_9 _ ->
                                                        false
                                                       | Section291_11_5 _ ->
                                                        false
                                                       | Section291_11_6 _ ->
                                                        false
                                                       | Section291_11 _ ->
                                                        false
                                                       | Section291_12 _ ->
                                                        false
                                                       | Section291_13 _ ->
                                                        false
                                                       | Section291_14 _ ->
                                                        false) ||
                                                       (match
                                                          (offense_.violation)
                                                       with
                                                       Section286_102 _ ->
                                                        false
                                                       | Section286_122 _ ->
                                                        false
                                                       | Section286_130 _ ->
                                                        false
                                                       | Section286_131 _ ->
                                                        false
                                                       | Section286_132 _ ->
                                                        false
                                                       | Section286_133 _ ->
                                                        false
                                                       | Section286_134 _ ->
                                                        true
                                                       | Section286_83_135 _ ->
                                                        false
                                                       | Section291_2 _ ->
                                                        false
                                                       | Section291_3_1 _ ->
                                                        false
                                                       | Section291_3_2 _ ->
                                                        false
                                                       | Section291_3_3 _ ->
                                                        false
                                                       | Section291_4_6 _ ->
                                                        false
                                                       | Section291_8 _ ->
                                                        false
                                                       | Section291_9 _ ->
                                                        false
                                                       | Section291_11_5 _ ->
                                                        false
                                                       | Section291_11_6 _ ->
                                                        false
                                                       | Section291_11 _ ->
                                                        false
                                                       | Section291_12 _ ->
                                                        false
                                                       | Section291_13 _ ->
                                                        false
                                                       | Section291_14 _ ->
                                                        false))))))))
                                  (fun (_: _) -> duration_of_numbers 0 0 30))|])
                          (fun (_: _) -> true)
                          (fun (_: _) -> duration_of_numbers 0 0 0))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    let min_fine_ : money =
      ((try
          (handle_default ([|(fun (_: _) -> min_fine_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default
                          ([|(fun (_: _) ->
                                handle_default ([||])
                                  (fun (_: _) -> paragraph_b_applies_)
                                  (fun (_: _) -> money_of_cents_string
                                     "50000"))|]) (fun (_: _) -> true)
                          (fun (_: _) -> money_of_cents_string "0"))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    let penalties_ : penalty array =
      ((try
          (handle_default ([|(fun (_: _) -> penalties_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default
                          ([|(fun (_: _) ->
                                handle_default ([||])
                                  (fun (_: _) -> paragraph_c_applies_)
                                  (fun (_: _) ->
                                     [|(Either
                                          ([|(LoseRightToDriveUntil18 ());
                                             (Fine
                                                {min_fine =
                                                   (money_of_cents_string
                                                   "50000");
                                                   max_fine =
                                                     (money_of_cents_string
                                                     "50000")})|]))|]))|])
                          (fun (_: _) -> true)
                          (fun (_: _) ->
                             [|(One
                                  (Imprisonment
                                     {min_days = (duration_of_numbers 0 0 0);
                                        max_days = max_days_}));
                               (One
                                  (Fine
                                     {min_fine = min_fine_;
                                        max_fine = max_fine_}))|]))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    {offense_out = offense_; defendant_out = defendant_;
       max_fine_out = max_fine_; min_fine_out = min_fine_;
       max_days_out = max_days_;
       priors_same_offense_out = priors_same_offense_;
       paragraph_b_applies_out = paragraph_b_applies_;
       paragraph_c_applies_out = paragraph_c_applies_;
       penalties_out = penalties_}

let s_291_11_6 =
  fun (s_291_11_6_in: s_291_11_6_in) ->
    let penalties_ : unit -> (penalty array) = (s_291_11_6_in.penalties_in)
    in
    let penalties_ : penalty array =
      ((try
          (handle_default ([|(fun (_: _) -> penalties_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||]) (fun (_: _) -> true)
                          (fun (_: _) ->
                             [|(One
                                  (Fine
                                     {min_fine = (money_of_cents_string
                                        "4500");
                                        max_fine = (money_of_cents_string
                                          "4500")}));
                               (One
                                  (Fee
                                     {min_fee = (money_of_cents_string
                                        "1000");
                                        max_fee = (money_of_cents_string
                                          "1000"); fund = (NeuroTrauma ())}));
                               (One
                                  (Fee
                                     {min_fee = (money_of_cents_string "0");
                                        max_fee = (money_of_cents_string
                                          "1000"); fund = (TraumaSystem ())}))|]))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    {penalties_out = penalties_}

let s_607_4 =
  fun (s_607_4_in: s_607_4_in) ->
    let violation_ : unit -> violation = (s_607_4_in.violation_in)
    in
    let category_ : unit -> fee_category = (s_607_4_in.category_in)
    in
    let penalty_ : unit -> penalty = (s_607_4_in.penalty_in)
    in
    let violation_ : violation =
      ((try
          (handle_default ([|(fun (_: _) -> violation_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default ([||]) (fun (_: _) -> false)
                  (fun (_: _) -> raise EmptyError))) with EmptyError ->
          (raise NoValueProvided)))
    in
    let category_ : fee_category =
      ((try
          (handle_default ([|(fun (_: _) -> category_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||])
                          (fun (_: _) -> (violation_ = (Section291_11_6 ())))
                          (fun (_: _) -> Paragraph9 ()))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    let penalty_ : penalty =
      ((try
          (handle_default ([|(fun (_: _) -> penalty_ ())|])
             (fun (_: _) -> true)
             (fun (_: _) ->
                handle_default
                  ([|(fun (_: _) ->
                        handle_default ([||])
                          (fun (_: _) -> (category_ = (Paragraph9 ())))
                          (fun (_: _) ->
                             One
                               (Fee
                                  {min_fee = (money_of_cents_string "3000");
                                     max_fee = (money_of_cents_string "3000");
                                     fund = (Clerk ())})))|])
                  (fun (_: _) -> false) (fun (_: _) -> raise EmptyError)))
          with EmptyError -> (raise NoValueProvided)))
    in
    {violation_out = violation_; category_out = category_;
       penalty_out = penalty_}